// <auto-generated />
using System;
using DoctorLicenseManagement.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoctorLicenseManagement.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoctorLicenseManagement.Domain.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LicenseExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Doctors_Email")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("LicenseExpiryDate")
                        .HasDatabaseName("IX_Doctors_ExpiryDate")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("LicenseNumber")
                        .HasDatabaseName("IX_Doctors_LicenseNumber")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Doctors_Status")
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 4, 6, 12, 26, 10, 168, DateTimeKind.Utc).AddTicks(5458),
                            Email = "john.smith@email.com",
                            FullName = "Dr. John Smith",
                            IsDeleted = false,
                            LicenseExpiryDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LicenseNumber = "MED123456",
                            Specialization = "Cardiology",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 4, 11, 12, 26, 10, 168, DateTimeKind.Utc).AddTicks(5467),
                            Email = "sarah.johnson@email.com",
                            FullName = "Dr. Sarah Johnson",
                            IsDeleted = false,
                            LicenseExpiryDate = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LicenseNumber = "MED789012",
                            Specialization = "Neurology",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 4, 16, 12, 26, 10, 168, DateTimeKind.Utc).AddTicks(5469),
                            Email = "michael.brown@email.com",
                            FullName = "Dr. Michael Brown",
                            IsDeleted = false,
                            LicenseExpiryDate = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LicenseNumber = "MED345678",
                            Specialization = "Pediatrics",
                            Status = "Expired"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 4, 21, 12, 26, 10, 168, DateTimeKind.Utc).AddTicks(5471),
                            Email = "emily.davis@email.com",
                            FullName = "Dr. Emily Davis",
                            IsDeleted = false,
                            LicenseExpiryDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LicenseNumber = "MED901234",
                            Specialization = "Orthopedics",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 4, 26, 12, 26, 10, 168, DateTimeKind.Utc).AddTicks(5473),
                            Email = "robert.wilson@email.com",
                            FullName = "Dr. Robert Wilson",
                            IsDeleted = false,
                            LicenseExpiryDate = new DateTime(2024, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LicenseNumber = "MED567890",
                            Specialization = "Dermatology",
                            Status = "Suspended"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
